#[derive(Clone, Debug, Eq, PartialEq)]
pub enum Capability {
    MultiAck,
    MultiAckDetailed,
    NoDone,
    ThinPack,
    SideBand,
    SideBand64k,
    OfsDelta,
    Agent(String),
    ObjectFormat(String),
    Symref(String, String),
    Shallow,
    NoProgress,
    ReportStatus,
    ReportStatusV2,
    DeleteRefs,
    Quiet,
    Atomic,
    PushOptions,
    AllowTipSha1InWant,
    AllowReachableSha1InWant,
    PushCert(String),
    Filter,
}
